# Generated by Django 5.2.4 on 2025-07-25 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_invitecode_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitecode',
            name='user',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='invite_code',
        ),
        migrations.AddField(
            model_name='invitecode',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='own_invite_code', to=settings.AUTH_USER_MODEL),
        ),
    ]
