openapi: 3.0.3
info:
  title: Referral system API
  version: 1.0.0
  description: Phone number authentication API with SMS codes and invite system.
paths:
  /api/schema/:
    get:
      operationId: api_schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - ug
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - api
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /api/token/refresh/:
    post:
      operationId: api_token_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefreshRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefreshRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefreshRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
  /auth/resend_code/:
    post:
      operationId: auth_resend_code_create
      tags:
      - Auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendCodeRequestRequest'
            examples:
              ResendCodeRequest:
                value:
                  phone: '+375291234567'
                summary: Resend code request
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/SendCodeRequestRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/SendCodeRequestRequest'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '201':
          description: Verification code resent successfully.
        '429':
          description: Too many requests.
  /auth/send_code/:
    get:
      operationId: auth_send_code_retrieve
      description: Send a 4-digit verification code to a Belarusian phone number.
      tags:
      - Auth
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: Returns the HTML page for sending the code.
    post:
      operationId: auth_send_code_create
      description: Send a 4-digit verification code to a Belarusian phone number.
      tags:
      - Auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendCodeRequestRequest'
            examples:
              SendCodeRequest:
                value:
                  phone: '+375291234567'
                summary: Send code request
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/SendCodeRequestRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/SendCodeRequestRequest'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: Code successfully sent.
        '400':
          description: Missing or invalid phone number.
        '429':
          description: Too many requests.
  /auth/verify_code/:
    post:
      operationId: auth_verify_code_create
      description: Verify the 4-digit code and return JWT tokens.
      tags:
      - Auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerifyCodeRequestRequest'
            examples:
              VerifyCodeRequest:
                value:
                  phone: '+375291234567'
                  code: '1234'
                summary: Verify code request
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/VerifyCodeRequestRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/VerifyCodeRequestRequest'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
              examples:
                VerifyCodeResponse:
                  value:
                    refresh: xxx
                    access: yyy
                    user_id: 1
                  summary: Verify code response
          description: ''
        '400':
          description: Missing/invalid data or code expired.
  /invite-code/use/:
    post:
      operationId: invite_code_use_create
      description: Apply another user's invite code. Can be done only once.
      tags:
      - User
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UseInviteCodeRequestRequest'
            examples:
              ApplyInviteCode:
                value:
                  invite_code: ABC123
                summary: Apply invite code
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UseInviteCodeRequestRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UseInviteCodeRequestRequest'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          description: Invite code successfully applied.
        '400':
          description: Invalid input or code already used.
        '404':
          description: Invite code not found.
        '401':
          description: Authentication credentials were not provided or invalid.
  /profile/:
    get:
      operationId: profile_retrieve
      description: Retrieve authenticated user's profile.
      tags:
      - User
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyUser'
          description: ''
        '401':
          description: Authentication credentials were not provided or invalid.
components:
  schemas:
    MyUser:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        phone:
          type: string
          maxLength: 15
        own_invite_code:
          type: string
        invited_by:
          $ref: '#/components/schemas/UserInviteCode'
        referrals:
          type: array
          items:
            $ref: '#/components/schemas/UserShort'
      required:
      - id
      - invited_by
      - own_invite_code
      - phone
      - referrals
    SendCodeRequestRequest:
      type: object
      properties:
        phone:
          type: string
          minLength: 1
          maxLength: 13
      required:
      - phone
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
      required:
      - access
      - refresh
    TokenRefreshRequest:
      type: object
      properties:
        refresh:
          type: string
          minLength: 1
      required:
      - refresh
    TokenResponse:
      type: object
      properties:
        refresh:
          type: string
          readOnly: true
        access:
          type: string
          readOnly: true
        user_id:
          type: integer
          readOnly: true
      required:
      - access
      - refresh
      - user_id
    UseInviteCodeRequestRequest:
      type: object
      properties:
        invite_code:
          type: string
          minLength: 1
          maxLength: 20
      required:
      - invite_code
    UserInviteCode:
      type: object
      properties:
        invite_code:
          type: string
      required:
      - invite_code
    UserShort:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        phone:
          type: string
          maxLength: 15
      required:
      - id
      - phone
    VerifyCodeRequestRequest:
      type: object
      properties:
        phone:
          type: string
          minLength: 1
          maxLength: 13
        code:
          type: string
          minLength: 1
          maxLength: 4
      required:
      - code
      - phone
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
